FROM node:24-alpine AS builder

WORKDIR /var/www/app

COPY package*.json ./

RUN npm i

COPY . .

RUN npm run build

FROM node:24-alpine AS production

WORKDIR /var/www/app

COPY --from=builder /var/www/app/dist ./dist/

EXPOSE 80

CMD []