FROM node:24-alpine AS builder

WORKDIR /var/www/app

COPY package*.json ./

RUN npm i

COPY . .

RUN npm run build

FROM node:24-alpine AS production

WORKDIR /var/www/app

COPY --from=builder /var/www/app/dist ./dist/
COPY --from=builder /var/www/app/package*.json ./

RUN npm ci --only=production

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]