FROM node:24-alpine AS builder

WORKDIR /var/www/app

COPY package*.json ./

RUN npm i

COPY . .

RUN npm run build

FROM nginx:1.29-alpine AS production

WORKDIR /var/www/app

COPY --from=builder /var/www/app/dist ./dist/
COPY ./default.conf /etc/nginx/conf.d/default.conf

EXPOSE 5173

CMD ["nginx", "-g", "daemon off;"]