server {
    listen 80;
    location /api/afisha {
        proxy_pass http://film-backend:8888;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /content {
        proxy_pass http://film-backend:8888;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location / {
        proxy_pass http://film-frontend:5173;
    }
}