services:
  backend-dev:
    restart: unless-stopped
    build:
      context: ../backend
      dockerfile: Dockerfile.dev
    image: film-backend:dev
    container_name: film-backend
    ports:
      - "8888:8888"
    volumes:
      - ../backend:/var/www/app
      - /var/www/app/node_modules
    env_file:
      - ../backend/.env
    profiles:
      - dev
    depends_on:
      - postgres
  backend-prod:
    restart: on-failure
    build:
      context: ../backend
      dockerfile: Dockerfile.production
    image: film-backend:prod
    container_name: film-backend
    ports:
      - "8888"
    env_file:
      - ../backend/.env
    profiles:
      - prod
    depends_on:
      - postgres

  frontend-dev:
    restart: unless-stopped
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    image: film-frontend:dev
    container_name: film-frontend
    ports:
      - "80:5173"
    volumes:
      - ../frontend:/var/www/app
      - /var/www/app/node_modules
    env_file:
      - ../frontend/.env
    profiles:
      - dev
  frontend-prod:
    restart: on-failure
    build:
      context: ../frontend
      dockerfile: Dockerfile.production
    image: film-frontend:prod
    container_name: film-frontend
    ports:
      - "80:5173"
    env_file:
      - ../frontend/.env
    profiles:
      - prod

  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./film_postgres_data:/var/lib/postgresql/data/pgdata

  pgadmin:
    image: elestio/pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.ru
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "8080:8080"

