name: Image publication to GHCR

env:
  REGISTRY: ghcr.io

on:
  push:
    paths:
      - './frontend/**'
      - './backend/**'
      - './deploy/nginx/**'
      - './deploy/prod/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - service: frontend
            context: ./frontend
            dockerfile: ./frontend/Dockerfile.prod
            name: frontend
          - service: backend
            context: ./backend
            dockerfile: ./backend/Dockerfile.prod
            name: backend
          - service: nginx
            context: ./deploy/nginx
            dockerfile: ./deploy/nginx/Dockerfile
            name: nginx

    permissions:
      contents: read
      packages: write

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Extract metadata for ${{ matrix.service }}
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{env.REGISTRY}}/${{ github.repository }}/${{ matrix.name }}

      - name: Build and push ${{ matrix.service }} image
        uses: docker/build-push-action@v5.3.0
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
                
