name: Build and push Backend

env:
  REGISTRY: ghcr.io

on:
  push:
    branches:
      - '**'
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{env.REGISTRY}}/${{ github.repository }}/backend

      - name: Build and push backend image
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./backend
          file: ./backend/Dockerfile.production
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
